config/routes.rb
Battler::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :jobs, only: [:index, :show]
  resources :characters, only: [:index, :show, :create, :new] do
    patch '/party/leave', to: 'parties#leave', as: :leave_party
  end
  resources :parties, only: [:index, :create]

  resource :dashboard, only: [:show]

end

app/models/application_record.rb
# frozen_string_literal: true
# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/char_class.rb
class CharClass < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/character.rb
# frozen_string_literal: true
# Character
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :party

  has_many :inventory_items
  has_many :items, through: :inventory_items

  has_many :enrolled_jobs
  has_many :jobs, through: :enrolled_jobs

  validates :name, presence: true, length: { in: 4..8 }, uniqueness: true
  validates :gender, presence: true, inclusion: { in: %w(Male Female) }

  after_save :add_starter

  def active_job
    enrolled_jobs.find_by(active: true)
  end

  # Increment the job level by 1 and return the new level.
  def active_job_level_up!
    active_job.update(level: active_job.level += 1)
    active_job.level
  end

  def change_active_job(job_alias)
    new_job_id = jobs.find_by(alias: job_alias)
    new_active_job = enrolled_jobs.find_by(job_id: new_job_id)

    active_job.update(active: false)
    new_active_job.update(active: true)
  end

  def list_jobs
    jobs = []
    enrolled_jobs.each do |enrolled_job|
      jobs << [enrolled_job.job.name, enrolled_job.level]
    end
    jobs
  end

  def list_inventory
    inventory = []
    inventory_items.includes(:item).each do |inventory_item|
      inventory << [inventory_item.item.name, inventory_item.quantity]
    end
    inventory
  end

  def list_inventory_types
    item_types = []
    items.each do |item|
      item_types << item.type
    end
    item_types.uniq
  end

  def list_consumables
    consumables = []
    inventory_items.includes(:item).each do |inventory_item|
      if inventory_item.item.type == 'Consumable'
        consumables << [inventory_item.item.name, inventory_item.quantity]
      end
    end
    consumables
  end

  def chest
    eq_lookup('chest')
  end

  def head
    eq_lookup('head')
  end

  def feet
    eq_lookup('feet')
  end

  def accessory1
    eq_lookup('accessory1')
  end

  def accessory2
    eq_lookup('accessory2')
  end

  def right
    eq_lookup('right')
  end

  def left
    eq_lookup('left')
  end

  def add_starter
    add_starter_jobs
    add_starter_items
    add_starter_skills
  end

  private

  def eq_lookup(slot)
    inventory_items.find_by(equipped: true, slot: slot)
  end

  def add_starter_jobs
    enrolled_jobs.create(job_id: 1, active: true)
  end

  def add_starter_items
  end

  def add_starter_skills
  end
end

app/models/enrolled_job.rb
# frozen_string_literal: true
# Enrolled Job
class EnrolledJob < ApplicationRecord
  belongs_to :job
  belongs_to :character
end

app/models/inventory_item.rb
# frozen_string_literal: true
# Inventory Item
class InventoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :character
end

app/models/item.rb
# frozen_string_literal: true
# Item
class Item < ActiveRecord::Base
  has_many :character_items
  has_many :characters, through: :inventory_items
end

app/models/job.rb
# frozen_string_literal: true
# Job
class Job < ActiveRecord::Base
  has_many :skills

  has_many :character_jobs
  has_many :characters, through: :enrolled_jobs

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/party.rb
# frozen_string_literal: true
# Party
class Party < ActiveRecord::Base
  has_many :characters
end

app/models/skill.rb
# frozen_string_literal: true
# Skill
class Skill < ActiveRecord::Base
  belongs_to :job
end

app/models/user.rb
# frozen_string_literal: true
# User
class User < ActiveRecord::Base
  has_one :character
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/battles_controller.rb
# frozen_string_literal: true
class BattlesController < ApplicationController
end

app/controllers/characters_controller.rb
# frozen_string_literal: true
# Characters
class CharactersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = current_user.create_character(character_params)
    if @character.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :gender)
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true
# Dashboard
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @character = current_user.character
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
# Home
class HomeController < ApplicationController
  def index
    redirect_to parties_path if current_user && current_user.character
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true
# Jobs
class JobsController < ApplicationController
  def index
    @jobs = Job.order(:id)
  end

  def show
    @job = Job.friendly.find(params[:id])
  end
end

app/controllers/parties_controller.rb
# frozen_string_literal: true
# Parties
class PartiesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_character, only: [:leave]

  def index
    @parties = Party.all
    @party = Party.new
  end

  def create
    @party = current_user.character.create_party(
      leader: current_user.character.name
    )
    current_user.character.save!
    redirect_to parties_path
  end

  def join
    current_user.character.party_id = params[:party_id]
    redirect_to parties_path
  end

  def leave
    current_character.update_attributes(party_id: nil)
    render text: "#{@character.name} has left the party."
  end

  def disband
    @party = Party.find(params[:party_id])
    party.delete
    redirect_to parties_path
  end

  private

  def require_authorized_for_character
    if current_character.user != current_user
      render text: 'Unauthorized', status: :Unauthorized
    end
  end

  def current_character
    @character = Character.find(params[:character_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
# Application
module ApplicationHelper
  def active_job_portrait(character)
    "/assets/portraits/#{character.active_job.job.alias.upcase}.gif"
  end

  def job_icon(character)
    "/assets/icons/#{character.active_job.job.alias.upcase}.png"
  end

  def current_character
    current_user.character
  end

  def equipment_name(slot)
    result = @character.inventory_items.find_by(equipped: true, slot: slot)
    result ? result.item.name : 'Empty'
  end
end

app/helpers/battles_helper.rb
# frozen_string_literal: true
# Battle
module BattlesHelper
end

app/helpers/characters_helper.rb
# frozen_string_literal: true
# Character
module CharactersHelper
  def job_names
    job_names = []
    Job.all.each do |job|
      job_names << job.name
    end
    job_names
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true
# Dashboard
module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true
# Home
module HomeHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true
# Jobs
module JobsHelper
end

app/helpers/parties_helper.rb
# frozen_string_literal: true
# Parties
module PartiesHelper
end

app/views/characters/index.html.slim
h1
  | Characters
br
- @characters.each do |character|
  .character-card
    = image_tag active_job_portrait(character)
    .pull-right
      h2
        = link_to character.name, character_path(character)
      #character-job
        = "Level #{character.active_job.level} #{character.active_job.job.name}"
      #character-jobs
        - character.list_jobs.each do |job_pair|
          = "#{job_pair[0]}:  #{job_pair[1]}"
          br

app/views/characters/new.html.slim
= simple_form_for @character do |f|
  = f.input :name
  = f.input :gender, collection: ["Male", "Female"]
  = f.button :submit
  

app/views/characters/show.html.slim
h1
  = @character.name
br
.container
  .row
    .inventory.col-xs-3.panel.col-xs-offset-1
      table
        - @character.list_inventory.each do |item_quantity|
          tr
            td[width="100"]
              = "#{item_quantity[0]}:"
            td
              = "#{item_quantity[1]}"
    .jobs.col-xs-3.panel.col-xs-offset-1
      table
        - @character.list_jobs.each do |job_level|
          tr
            td[width="100"]
              = "#{job_level[0]}:"
            td
              = "#{job_level[1]}"

app/views/jobs/index.html.slim
h1
  | Jobs
br
ol.breadcrumb
  li.active
    | Jobs
- @jobs.each do |job|
  = image_tag "/assets/icons/#{job.alias}.png", class: 'job-icon'
  = link_to job.name, job_path(job)
  br
  br

app/views/jobs/show.html.slim
h1
  | Jobs
br
ol.breadcrumb
  li
    = link_to 'Jobs', jobs_path
  li.active
    = @job.name
p
  = image_tag "/assets/icons/#{@job.alias}.png", class: 'job-icon'
  = @job.description

app/views/parties/index.html.slim
h1 Parties
.container
  #parties.col-xs-12.text-center
    - if ! current_user.character.party
      = simple_form_for @party do |f|
        = f.button :submit
    - else
      = link_to 'Leave Party', character_leave_party_path(current_user.character.id), id: 'leave-party', method: :patch, data: {character: current_user.character.id}
    - @parties.each do |party|
      .row
        #party-row-header.col-xs-1
          = party.id   
        #party-row.col-xs-11
          - party.characters.each do |member|
            .party-character-card
              = member.name
              br
              = image_tag (member.active_job_portrait)
              br
              br
              = "#{member.active_character_job.level} #{member.active_character_job.job.name}"
      