config/routes.rb
Battler::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :jobs, only: [:index, :show]
  resources :characters, only: [:index, :show, :create, :new] do
    patch '/party/leave', to: 'parties#leave', as: :leave_party
  end
  resources :parties, only: [:index, :create]

  resource :dashboard, only: [:show]

end

app/models/application_record.rb
# frozen_string_literal: true
# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/char_class.rb
class CharClass < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/character.rb
# frozen_string_literal: true
# Character
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :party

  has_many :inventory_items
  has_many :items, through: :inventory_items

  has_many :enrolled_jobs
  has_many :jobs, through: :enrolled_jobs

  validates :name, presence: true, length: { in: 4..8 }, uniqueness: true
  validates :gender, presence: true, inclusion: { in: %w(Male Female) }

  after_save :add_starter

  def active_job
    enrolled_jobs.find_by(active: true)
  end

  # Increment the job level by 1 and return the new level.
  def active_job_level_up!
    active_job.update(level: active_job.level += 1)
    active_job.level
  end

  def change_active_job(job_alias)
    new_job_id = jobs.find_by(alias: job_alias)
    new_active_job = enrolled_jobs.find_by(job_id: new_job_id)

    active_job.update(active: false)
    new_active_job.update(active: true)
  end

  def list_jobs
    jobs = []
    enrolled_jobs.each do |enrolled_job|
      jobs << [enrolled_job.job.name, enrolled_job.level]
    end
    jobs
  end

  def list_inventory
    inventory = []
    inventory_items.includes(:item).each do |inventory_item|
      inventory << [inventory_item.item.name, inventory_item.quantity]
    end
    inventory
  end

  def list_inventory_types
    item_types = []
    items.each do |item|
      item_types << item.type
    end
    item_types.uniq
  end

  def list_consumables
    consumables = []
    inventory_items.includes(:item).each do |inventory_item|
      if inventory_item.item.type == 'Consumable'
        consumables << [inventory_item.item.name, inventory_item.quantity]
      end
    end
    consumables
  end

  def chest
    eq_lookup('chest')
  end

  def head
    eq_lookup('head')
  end

  def feet
    eq_lookup('feet')
  end

  def accessory1
    eq_lookup('accessory1')
  end

  def accessory2
    eq_lookup('accessory2')
  end

  def right
    eq_lookup('right')
  end

  def left
    eq_lookup('left')
  end

  def add_starter
    add_starter_jobs
    add_starter_items
    add_starter_skills
  end

  private

  def eq_lookup(slot)
    inventory_items.find_by(equipped: true, slot: slot)
  end

  def add_starter_jobs
    enrolled_jobs.create(job_id: 1, active: true)
  end

  def add_starter_items
  end

  def add_starter_skills
  end
end

app/models/enrolled_job.rb
# frozen_string_literal: true
# Enrolled Job
class EnrolledJob < ApplicationRecord
  belongs_to :job
  belongs_to :character
end

app/models/inventory_item.rb
# frozen_string_literal: true
# Inventory Item
class InventoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :character
end

app/models/item.rb
# frozen_string_literal: true
# Item
class Item < ActiveRecord::Base
  has_many :character_items
  has_many :characters, through: :inventory_items
end

app/models/job.rb
# frozen_string_literal: true
# Job
class Job < ActiveRecord::Base
  has_many :skills

  has_many :character_jobs
  has_many :characters, through: :enrolled_jobs

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/party.rb
# frozen_string_literal: true
# Party
class Party < ActiveRecord::Base
  has_many :characters
end

app/models/skill.rb
# frozen_string_literal: true
# Skill
class Skill < ActiveRecord::Base
  belongs_to :job
end

app/models/user.rb
# frozen_string_literal: true
# User
class User < ActiveRecord::Base
  has_one :character
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/battles_controller.rb
# frozen_string_literal: true
class BattlesController < ApplicationController
end

app/controllers/home_controller.rb
# frozen_string_literal: true
# Home
class HomeController < ApplicationController
  def index
    redirect_to parties_path if current_user && current_user.character
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true
# Jobs
class JobsController < ApplicationController
  def index
    @jobs = Job.order(:id)
  end

  def show
    @job = Job.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
# Application
module ApplicationHelper
  def active_job_portrait(character)
    "/assets/portraits/#{character.active_job.job.alias.upcase}.gif"
  end

  def job_icon(character)
    "/assets/icons/#{character.active_job.job.alias.upcase}.png"
  end

  def current_character
    current_user.character
  end

  def equipment_name(slot)
    result = @character.inventory_items.find_by(equipped: true, slot: slot)
    result ? result.item.name : 'Empty'
  end
end

app/helpers/battles_helper.rb
# frozen_string_literal: true
# Battle
module BattlesHelper
end

app/helpers/characters_helper.rb
# frozen_string_literal: true
# Character
module CharactersHelper
  def job_names
    job_names = []
    Job.all.each do |job|
      job_names << job.name
    end
    job_names
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true
# Dashboard
module DashboardsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true
# Home
module HomeHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true
# Jobs
module JobsHelper
end

app/helpers/parties_helper.rb
# frozen_string_literal: true
# Parties
module PartiesHelper
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-inverse
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Battler', root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.dropdown
          a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
            span.glyphicon.glyphicon-book
            |  Guide 
            span.caret
          ul.dropdown-menu
            li
              = link_to 'Jobs', jobs_path
            li
              = link_to 'Skills', '#'
            li
              = link_to 'Beastiary', '#'
        li
          = link_to characters_path do
            span.glyphicon.glyphicon-user
            |  Characters 
        li
          = link_to '#' do
            span.glyphicon.glyphicon-comment
            |  Forum 
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in? && current_character
          li
            = link_to image_tag(active_job_portrait(current_character), class: 'character-icon'), dashboard_path
          li#nav-character-panel
            = "#{current_character.name}"
        li.dropdown
          a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
            |  Account 
            span.caret
          ul.dropdown-menu
            - if user_signed_in?
              - if !current_character
              li
                = link_to new_character_path do
                  span.glyphicon.glyphicon-plus
                  |   New Character
                end
              li
                = link_to '#' do
                  span.glyphicon.glyphicon-cog
                  |   Settings 
              li
                = link_to destroy_user_session_path, method: :delete do
                  span.glyphicon.glyphicon-log-out
                  |   Logout 
            - else
              li
                = link_to new_user_session_path do
                  span.glyphicon.glyphicon-log-in
                  |   Log In 
              li
                = link_to new_user_registration_path do
                  span.glyphicon.glyphicon-plus
                  |   New Account 

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Battler
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    meta[name="viewport" content="width=device-width, initial-scale=1"]
  body
    = render "layouts/navbar"
    - if notice.present?
      p.alert.alert-info.text-center
        = notice
    - if alert.present?
      p.alert.alert-danger.text-center
        = alert
    #main
      = yield